# Generated by Django 3.2.3 on 2021-05-28 17:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SEM', models.IntegerField()),
                ('SUBCODE', models.IntegerField()),
                ('SUBJECT_NAME', models.CharField(max_length=100)),
                ('CRD', models.IntegerField()),
                ('GRD', models.CharField(max_length=1)),
                ('RESULT_DATE', models.DateField()),
                ('BRANCH', models.CharField(max_length=60)),
                ('SEAT_NO', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
