# Generated by Django 3.2.3 on 2021-05-28 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultProfile',
        ),
    ]
