# Generated by Django 3.2.3 on 2021-05-28 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_resultprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultProfile',
        ),
    ]
