# Generated by Django 3.2.3 on 2021-05-29 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_resultprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultProfile',
        ),
    ]
