# Generated by Django 3.2.3 on 2021-05-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_resultprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=20)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('SUBJECT', models.CharField(max_length=50)),
                ('MESSAGE', models.CharField(max_length=200)),
            ],
        ),
    ]
