# Generated by Django 3.2.3 on 2021-06-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_admissionenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultprofile',
            name='ERP',
            field=models.CharField(max_length=7),
        ),
    ]
